Create person, student and teacher classes.
fuadmoin/school-library pull request #1
Opened 2023-05-22 16:12 UTC by fuadmoin

In this branch I: 

- [ ] created a class person.
- [ ] created a class student that inherits a class person.
- [ ] created a class teacher that inherits a class person.
- [ ] updated readme

2023-05-22 19:14 UTC, Olamarx requested changes
Hi @fuadmoin, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does have a link that is not associated with the project in the readme file.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-05-22 19:14 UTC, Olamarx commented on README.md
> +You can deploy this project using [Render](https://render.com/).
- [ ] Since you are not publishing this, I would implore to remove the link.

2023-05-22 20:03 UTC, codecaiine requested changes
Hi @fuadmoin , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
- Good class implementation setup ✔️ 
- No rubocop errors ✔️ 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me (@codecaiine) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-22 20:03 UTC, codecaiine commented on library.rb
> +class Person
- [ ] I would strongly recommend you create an individual .rb file for each class **Person**, **Student**, and **Teacher** . because it offers several advantages like **Code organization**, **Reusability**, **Consistency and clarity**, **Dependency management** 👍

2023-05-22 20:03 UTC, codecaiine commented on library.rb
> +  attr_reader :id
- [ ] [OPTIONAL] I would like to recommend you define getter and setter methods before other functions within a class. This helps maintain a consistent structure and makes the code more readable. 👍 

```
class MyClass
  attr_reader :my_attribute  # Getter method
  
  attr_writer :my_attribute  # Setter method

  def initialize(my_attribute)
    @my_attribute = my_attribute
  end

  def some_function
    # Code for some_function
  end

  def another_function
    # Code for another_function
  end
  
  # More functions...
end

```

2023-05-23 09:46 UTC, rotimiazeez approved these changes
Hi @fuadmoin 👏🏽, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- Good job implementing the required changes 👍🏽
- Good code organization 👌🏽
- Descriptive PR title and summary 💪🏽

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-23 09:53 UTC, merged